name: orh
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.85=py310ha75aee5_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cffi=1.17.1=py310h8deb56e_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - ld_impl_linux-64=2.44=h1423503_0
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgomp=15.1.0=h767d61c_3
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libsqlite=3.50.2=h6cd9bfd_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mummer=3.23=pl5321h503566f_21
  - ncbi-datasets-cli=18.4.0=ha770c72_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.6=py310hefbff90_0
  - openssl=3.5.1=h7b32b05_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=25.1.1=pyh8b19718_0
  - pycparser=2.22=pyh29332c3_1
  - python=3.10.12=hd12c33a_0_cpython
  - python_abi=3.10=7_cp310
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha75aee5_2
  - pip:
      - altair==5.5.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2025.6.15
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.58.5
      - geographiclib==2.1
      - geopy==2.4.1
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.10
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - narwhals==1.48.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - python-decouple==3.8
      - pytz==2025.2
      - pyyaml==6.0.2
      - recombinhunt==7.0.0
      - seaborn==0.13.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - streamlit==1.47.1
      - streamlit-aggrid==1.1.8.post1
      - streamlit-js-eval==0.1.7
      - streamlit-option-menu==0.4.0
      - toml==0.10.2
      - urllib3==2.5.0
      - watchdog==6.0.0
      - webencodings==0.5.1
prefix: /home/topcuoglu/miniconda3/envs/orh
