channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.85
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cffi=1.17.1
  - colorama=0.4.6
  # - fqdn=1.5.1
  - geographiclib=2.1
  - geopy=2.4.1
  # - isoduration=20.11.0
  # - jsonpointer=3.0.0
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.50.2
  - libstdcxx=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mummer=3.23
  - ncbi-datasets-cli=18.4.0
  - ncurses=6.5
  - numpy=2.2.6
  - openssl=3.5.1
  - perl=5.32.1
  - pip=25.1.1
  - pycparser=2.22
  - python=3.10.12
  - python_abi=3.10
  - python-decouple=3.8
  - readline=8.2
  - seaborn=0.13.2
  - setuptools=80.9.0
  - streamlit=1.47.1
  - streamlit-aggrid=1.1.8.post1
  - tk=8.6.13
  - tqdm=4.67.1
  # - tinycss2=1.4.0
  - tzdata=2025b
  # - uri-template=1.3.0
  # - webcolors=24.11.1
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstandard=0.23.0
  - pip:
      - altair==5.5.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2025.6.15
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.58.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - git-filter-repo==2.47.0
      - idna==3.10
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - narwhals==1.48.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - streamlit-js-eval==0.1.7
      - streamlit-option-menu==0.4.0
      - toml==0.10.2
      - urllib3==2.5.0
      - watchdog==6.0.0
      - webencodings==0.5.1
